#! /bin/bash
#
# example launch script that sets up the GIR path and launches
# astroid from the source root directory, unbuffered, and logging to
# ~/.config/astroid/log
#
# IMPORTANT: This assumes that you build astroid in the 'build' sub-directory.
#
# Symlink this to somewhere on your path.
#

ASTROID_DIR=$(readlink -f $0)
export ASTROID_DIR=$(dirname $ASTROID_DIR)/..

# GIR
export GI_TYPELIB_PATH=$ASTROID_DIR/build

unbuffer $ASTROID_DIR/build/astroid -l ~/.config/astroid/log $*

