#! /bin/bash
#
# example launch script that sets up the GIR path and launches
# astroid from the source root directory, unbuffered, and logging to
# ~/.config/astroid/log
#
# symlink this to somewhere on your path.
#

ASTROID_DIR=$(readlink -f $0)
export ASTROID_DIR=$(dirname $ASTROID_DIR)/..

# GIR
export GI_TYPELIB_PATH=$ASTROID_DIR

unbuffer $ASTROID_DIR/astroid -l ~/.config/astroid/log $*

